Repository woowa-camp-2023-4/backend, pull requests merged in 2023-08, with the labels that each got.

#34 feat: 재고 추가 기능 (#9)
  src/main/java/com/woowa/woowakit/domain/model/Quantity.java
  src/main/java/com/woowa/woowakit/domain/model/converter/QuantityConverter.java
  src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
  src/main/java/com/woowa/woowakit/domain/product/application/ProductService.java
  src/main/java/com/woowa/woowakit/domain/product/application/StockService.java
  src/main/java/com/woowa/woowakit/domain/product/domain/converter/ProductQuantityConverter.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/Product.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductImage.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductName.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductPrice.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductRepository.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductStatus.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/converter/ProductImageConverter.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/converter/ProductNameConverter.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/converter/ProductPriceConverter.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/ExpiryDate.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/Stock.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/StockRepository.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/converter/ExpiryDateConverter.java
  src/main/java/com/woowa/woowakit/domain/product/dto/request/ProductCreateRequest.java
  src/main/java/com/woowa/woowakit/domain/product/dto/request/StockCreateRequest.java
  src/main/java/com/woowa/woowakit/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/com/woowa/woowakit/domain/product/exception/.gitkeep
  src/main/java/com/woowa/woowakit/domain/product/exception/StockExpiredException.java
  src/main/java/com/woowa/woowakit/domain/product/exception/StockQuantityNegativeException.java
  src/main/resources/schema.sql
  src/test/java/com/woowa/woowakit/domain/model/QuantityTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/ProductQuantityTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/product/ProductTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/ExpiryDateTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StockRepositoryTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StockTest.java
  src/test/java/integration/product/ProductIntegrationTest.java
  src/test/resources/application.yml
Labels: feature, Pair

#37 feat: Order Entity 생성
  src/main/java/com/woowa/woowakit/domain/order/domain/Order.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderItem.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderStatus.java
  src/main/java/com/woowa/woowakit/domain/order/domain/Payment.java
  src/main/java/com/woowa/woowakit/domain/order/domain/TotalPrice.java
  src/main/java/com/woowa/woowakit/domain/order/domain/converter/TotalPriceConverter.java
  src/main/resources/schema.sql
Labels: Pair

#41 feat: 장바구니에 상품을 추가하는 기능 구현 및 상품 상태를 변경하는 기능 구현 #7 # 23
  src/main/java/com/woowa/woowakit/domain/cart/api/CartItemController.java
  src/main/java/com/woowa/woowakit/domain/cart/application/CartItemService.java
  src/main/java/com/woowa/woowakit/domain/cart/domain/CartItem.java
  src/main/java/com/woowa/woowakit/domain/cart/domain/CartItemRepository.java
  src/main/java/com/woowa/woowakit/domain/cart/domain/CartItemValidator.java
  src/main/java/com/woowa/woowakit/domain/cart/dto/CartItemAddRequest.java
  src/main/java/com/woowa/woowakit/domain/cart/exception/CartException.java
  src/main/java/com/woowa/woowakit/domain/cart/exception/CartItemNotExistException.java
  src/main/java/com/woowa/woowakit/domain/cart/exception/CartItemQuantityException.java
  src/main/java/com/woowa/woowakit/domain/cart/exception/InvalidProductInCartItemException.java
  src/main/java/com/woowa/woowakit/domain/cart/exception/ProductNotExistException.java
  src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
  src/main/java/com/woowa/woowakit/domain/product/application/ProductService.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/Product.java
  src/main/java/com/woowa/woowakit/domain/product/dto/request/ProductStatusUpdateRequest.java
  src/main/java/com/woowa/woowakit/domain/product/exception/UpdateProductStatusFailException.java
  src/main/resources/schema.sql
  src/test/java/com/woowa/woowakit/domain/cart/domain/CartItemTest.java
  src/test/java/com/woowa/woowakit/domain/cart/domain/CartItemValidatorTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/product/ProductTest.java
  src/test/java/integration/cart/CartIntegrationTest.java
  src/test/java/integration/helper/CartItemHelper.java
  src/test/java/integration/helper/CommonRestAssuredUtils.java
  src/test/java/integration/helper/ProductHelper.java
  src/test/java/integration/product/ProductIntegrationTest.java
  src/test/resources/application.yml
Labels: feature, 장바구니

#42 주문하기 기능 추가 (미완성) - 논의 주제
  build.gradle
  src/main/java/com/woowa/woowakit/domain/model/Image.java
  src/main/java/com/woowa/woowakit/domain/model/Money.java
  src/main/java/com/woowa/woowakit/domain/model/Quantity.java
  src/main/java/com/woowa/woowakit/domain/model/converter/ImageConverter.java
  src/main/java/com/woowa/woowakit/domain/model/converter/MoneyConverter.java
  src/main/java/com/woowa/woowakit/domain/model/converter/QuantityConverter.java
  src/main/java/com/woowa/woowakit/domain/order/application/OrderMapper.java
  src/main/java/com/woowa/woowakit/domain/order/application/OrderService.java
  src/main/java/com/woowa/woowakit/domain/order/application/PaymentService.java
  src/main/java/com/woowa/woowakit/domain/order/domain/Order.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderItem.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderItemStock.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderRepository.java
  src/main/java/com/woowa/woowakit/domain/order/domain/TotalPrice.java
  src/main/java/com/woowa/woowakit/domain/order/domain/converter/TotalPriceConverter.java
  src/main/java/com/woowa/woowakit/domain/order/domain/validator/OrderValidator.java
  src/main/java/com/woowa/woowakit/domain/order/domain/validator/OrderValidatorImpl.java
  src/main/java/com/woowa/woowakit/domain/order/dto/request/OrderCreateRequest.java
  src/main/java/com/woowa/woowakit/domain/order/dto/request/PreOrderCreateRequest.java
  src/main/java/com/woowa/woowakit/domain/order/dto/response/OrderItemResponse.java
  src/main/java/com/woowa/woowakit/domain/order/dto/response/PreOrderResponse.java
  src/main/java/com/woowa/woowakit/domain/order/exception/NotMyOrderException.java
  src/main/java/com/woowa/woowakit/domain/order/exception/OrderException.java
  src/main/java/com/woowa/woowakit/domain/order/exception/OrderNotFoundException.java
  src/main/java/com/woowa/woowakit/domain/order/exception/ProductNotFoundException.java
  src/main/java/com/woowa/woowakit/domain/order/exception/QuantityNotEnoughException.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/Product.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductRepository.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/ItemStock.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/Stock.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/StockRepository.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/Stocks.java
  src/main/java/com/woowa/woowakit/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/com/woowa/woowakit/infra/payment/toss/TossPaymentClient.java
  src/main/java/com/woowa/woowakit/infra/payment/toss/dto/TossPaymentRequest.java
  src/main/resources/schema.sql
  src/test/java/com/woowa/woowakit/domain/model/MoneyTest.java
  src/test/java/com/woowa/woowakit/domain/model/QuantityTest.java
  src/test/java/com/woowa/woowakit/domain/order/application/OrderServiceTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StockTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StocksTest.java
  src/test/java/com/woowa/woowakit/infra/payment/toss/TossPaymentClientTest.java
Labels: feature, Pair

#46 test: 주문 controller추가, 주문 관련 단위테스트, 통합테스트 추가
  src/main/java/com/woowa/woowakit/domain/order/api/OrderController.java
  src/main/java/com/woowa/woowakit/domain/order/domain/Order.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderItem.java
  src/main/java/com/woowa/woowakit/global/config/PayConfig.java
  src/test/java/com/woowa/woowakit/domain/order/domain/validator/OrderValidatorImplTest.java
  src/test/java/com/woowa/woowakit/domain/order/fixture/OrderFixture.java
  src/test/java/integration/helper/MemberHelper.java
  src/test/java/integration/helper/OrderHelper.java
  src/test/java/integration/helper/ProductHelper.java
  src/test/java/integration/order/OrderIntegrationTest.java
Labels: enhancement, feature

#55 feat: 상품을 조건에 따라 검색할 수 있다. #6
  build.gradle
  src/main/java/com/woowa/woowakit/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/woowa/woowakit/domain/auth/dto/request/SignUpRequest.java
  src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
  src/main/java/com/woowa/woowakit/domain/product/application/ProductService.java
  src/main/java/com/woowa/woowakit/domain/product/dao/.gitkeep
  src/main/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryCustom.java
  src/main/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryCustomImpl.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/Product.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductName.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductRepository.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductSearchCondition.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/converter/ProductNameConverter.java
  src/main/java/com/woowa/woowakit/domain/product/dto/request/ProductSearchRequest.java
  src/main/java/com/woowa/woowakit/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/com/woowa/woowakit/global/config/QuerydslConfig.java
  src/test/java/com/woowa/woowakit/domain/member/application/AuthServiceTest.java
  src/test/java/com/woowa/woowakit/domain/order/application/OrderServiceTest.java
  src/test/java/com/woowa/woowakit/domain/order/domain/validator/OrderValidatorImplTest.java
  src/test/java/com/woowa/woowakit/domain/product/application/ProductServiceTest.java
  src/test/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StockRepositoryTest.java
  src/test/java/com/woowa/woowakit/global/config/QuerydslTestConfig.java
  src/test/java/com/woowa/woowakit/global/interceptor/AuthenticationInterceptorTest.java
  src/test/java/integration/product/ProductIntegrationTest.java
Labels: 상품 관리, feature

#57 feat: 본인의 주문 내역을 확인할 수 있다. #15
  src/main/java/com/woowa/woowakit/domain/order/api/OrderController.java
  src/main/java/com/woowa/woowakit/domain/order/application/OrderService.java
  src/main/java/com/woowa/woowakit/domain/order/domain/Order.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderRepository.java
  src/main/java/com/woowa/woowakit/domain/order/dto/response/OrderDetailResponse.java
  src/main/java/com/woowa/woowakit/domain/order/dto/response/OrderItemResponse.java
  src/test/java/com/woowa/woowakit/domain/order/application/OrderServiceTest.java
  src/test/java/com/woowa/woowakit/domain/order/dao/OrderRepositoryTest.java
  src/test/java/integration/order/OrderIntegrationTest.java
Labels: feature, 주문 관리, P2

#62 로깅 저장 위치 변경
  src/main/resources/logback-variables.properties
Labels: documentation

#63 로깅 저장 위치 변경
  src/main/resources/logback-variables.properties
Labels: documentation

#66 refactor: Order -> Product 의존성 수정
  src/main/java/com/woowa/woowakit/domain/order/domain/Order.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderCompleteEvent.java
  src/main/java/com/woowa/woowakit/domain/order/domain/event/OrderCompleteEvent.java
  src/main/java/com/woowa/woowakit/domain/order/domain/handler/ProductQuantityEventHandler.java
  src/main/java/com/woowa/woowakit/domain/payment/domain/PaymentHandler.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductQuantityEventHandler.java
Labels: feature

#70 feat: 이미지 업로드 url 추가
  build.gradle
  src/main/java/com/woowa/woowakit/domain/product/api/ProductImageController.java
  src/main/java/com/woowa/woowakit/domain/product/application/ImageUploader.java
  src/main/java/com/woowa/woowakit/global/error/CommonExceptionHandler.java
  src/main/java/com/woowa/woowakit/infra/aws/s3/S3ImageUploader.java
  src/main/java/com/woowa/woowakit/infra/aws/s3/S3Uploader.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/integration/product/ProductImageIntegrationTest.java
  src/test/resources/application.yml
Labels: feature

#67 feat: 장바구니에서 상품을 주문할 수 있다. #13
  src/main/java/com/woowa/woowakit/domain/auth/domain/Member.java
  src/main/java/com/woowa/woowakit/domain/cart/domain/CartItemRepository.java
  src/main/java/com/woowa/woowakit/domain/order/api/OrderController.java
  src/main/java/com/woowa/woowakit/domain/order/application/OrderService.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderMapper.java
  src/main/java/com/woowa/woowakit/domain/order/domain/handler/CartItemDeletionEventHandler.java
  src/main/java/com/woowa/woowakit/domain/order/dto/request/PreOrderCreateCartItemRequest.java
  src/main/java/com/woowa/woowakit/domain/order/dto/response/OrderItemResponse.java
  src/main/java/com/woowa/woowakit/domain/order/exception/CartItemNotFoundException.java
  src/test/java/com/woowa/woowakit/domain/cart/domain/CartItemRepositoryTest.java
  src/test/java/com/woowa/woowakit/domain/member/fixture/MemberFixture.java
  src/test/java/com/woowa/woowakit/domain/order/application/OrderServiceConcurrencyTest.java
  src/test/java/com/woowa/woowakit/domain/order/application/OrderServiceTest.java
  src/test/java/com/woowa/woowakit/domain/product/fixture/ProductFixture.java
  src/test/java/integration/helper/CartItemHelper.java
  src/test/java/integration/helper/OrderHelper.java
  src/test/java/integration/order/OrderIntegrationTest.java
Labels: feature

#72 자정에 재고와 상품 수량 정합성 , 재고에 유통기한 정책 적용 #64
  src/main/java/com/woowa/woowakit/domain/order/api/OrderController.java
  src/main/java/com/woowa/woowakit/domain/order/domain/Order.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderItem.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderMapper.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderRepository.java
  src/main/java/com/woowa/woowakit/domain/order/dto/request/PreOrderCreateCartItemRequest.java
  src/main/java/com/woowa/woowakit/domain/order/dto/request/PreOrderCreateRequest.java
  src/main/java/com/woowa/woowakit/domain/order/dto/response/PreOrderResponse.java
  src/main/java/com/woowa/woowakit/domain/product/application/StockProcessingService.java
  src/main/java/com/woowa/woowakit/domain/product/application/StockScheduler.java
  src/main/java/com/woowa/woowakit/domain/product/application/StockService.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductRepository.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/ExpirationDateProcessor.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/ExpiryDate.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/ItemStock.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/Stock.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/StockConsistencyProcessor.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/StockRepository.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/StockType.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/Stocks.java
  src/main/java/com/woowa/woowakit/global/config/SchedulingConfig.java
  src/main/resources/schema.sql
  src/test/java/com/woowa/woowakit/domain/product/application/StockProcessingServiceTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/ExpirationDateProcessorTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StockConsistencyProcessorTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StockRepositoryTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StockTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StocksTest.java
  src/test/resources/application.yml
Labels: feature, 재고 관리

#77 주문에서 주문 아이템 상품에 재고를 확보하는 로직에서 N+1 문제 해결하기 #76
  src/main/java/com/woowa/woowakit/domain/order/domain/handler/ProductQuantityEventHandler.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductRepository.java
Labels: advanced

#80 데이터베이스 테이블 대문자 -> 소문자로 변경
  src/main/java/com/woowa/woowakit/domain/auth/domain/Member.java
  src/main/java/com/woowa/woowakit/domain/cart/domain/CartItem.java
  src/main/java/com/woowa/woowakit/domain/payment/domain/Payment.java
  src/main/java/com/woowa/woowakit/domain/payment/domain/PaymentHandler.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/Product.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/Stock.java
  src/main/java/com/woowa/woowakit/global/config/WebClientConfig.java
  src/main/resources/schema.sql
Labels: bug, refactor

#82 webClient 타임아웃 시간 1초 -> 3초
  src/main/java/com/woowa/woowakit/global/config/WebClientConfig.java
  src/main/resources/application.yml
Labels: bug

#83 fix: prod.yml 및 오류 해결
  src/main/java/com/woowa/woowakit/domain/product/application/StockProcessingService.java
  src/main/java/com/woowa/woowakit/global/error/CommonExceptionHandler.java
  src/main/resources/application-prod.yml
Labels: bug

#84 feat: 메트릭 모니터링 설정 추가
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feature

#85 feat: deploy 환경 변수 추가, 로그 보강
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
Labels: enhancement

#87 fix: 결제 성능 테스트를 위해 Thread sleep 빈으로 변경
  src/main/java/com/woowa/woowakit/global/config/PayConfig.java
  src/main/java/com/woowa/woowakit/infra/payment/toss/ThreadSleepClient.java
  src/main/java/com/woowa/woowakit/infra/payment/toss/TossPaymentClient.java
  src/test/java/com/woowa/woowakit/infra/payment/toss/ThreadSleepClientTest.java
Labels: enhancement

#88 fix: order, auth 로그 보강
  src/main/java/com/woowa/woowakit/domain/order/application/OrderService.java
  src/main/java/com/woowa/woowakit/domain/order/domain/Order.java
  src/main/java/com/woowa/woowakit/domain/order/domain/handler/CartItemDeletionEventHandler.java
  src/main/java/com/woowa/woowakit/domain/order/domain/handler/ProductQuantityEventHandler.java
  src/main/java/com/woowa/woowakit/global/interceptor/AuthenticationInterceptor.java
Labels: enhancement

#90 재고 정합성 스케쥴러 로깅 추가
  src/main/java/com/woowa/woowakit/domain/product/application/StockScheduler.java
Labels: enhancement

#91 feat: unique key 에러 추가
  src/main/java/com/woowa/woowakit/global/error/CommonExceptionHandler.java
Labels: bug, enhancement

#94 StockScheduler 임시 앤드포인트 추가
  src/main/java/com/woowa/woowakit/domain/product/api/StockSchedulerController.java
Labels: enhancement

#96 feat: 일일 판매량 순으로 조회할 수 있도록 변경
  src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
  src/main/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryCustomImpl.java
  src/main/java/com/woowa/woowakit/domain/product/domain/ProductSalesRepository.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductName.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductSales.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductSearchCondition.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/SaleQuantity.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/StockConsistencyProcessor.java
  src/main/java/com/woowa/woowakit/domain/product/dto/request/ProductSearchRequest.java
  src/main/resources/schema.sql
  src/test/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StockConsistencyProcessorTest.java
Labels: 상품 관리

#99 feat: 상품을 일일 판매량 순으로 조회할 수 있다. 이름을 바탕으로 검색할 수 있다. (#98)
  src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
  src/main/java/com/woowa/woowakit/domain/product/application/ProductService.java
  src/main/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryCustom.java
  src/main/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryCustomImpl.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductSearchCondition.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductSpecification.java
  src/main/java/com/woowa/woowakit/domain/product/dto/request/ProductSearchRequest.java
  src/main/java/com/woowa/woowakit/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/com/woowa/woowakit/domain/product/dto/response/ProductResponse.java
  src/test/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryTest.java
  src/test/java/integration/helper/ProductHelper.java
  src/test/java/integration/product/ProductIntegrationTest.java
Labels: 상품 관리, advanced

#102 fix: 이름이 같으면 기존 이미지가 새 이미지에 덮어쓰기 되는 문제 해결
  src/main/java/com/woowa/woowakit/infra/aws/s3/S3ImageUploader.java
  src/main/java/com/woowa/woowakit/infra/aws/s3/S3Uploader.java
Labels: bug

#105 feat: 결제 비동기 처리되도록 변경 (장애 대응 후속 조치 필요)
  src/main/java/com/woowa/woowakit/WoowakitApplication.java
  src/main/java/com/woowa/woowakit/domain/order/api/OrderController.java
  src/main/java/com/woowa/woowakit/domain/payment/domain/PaySaveService.java
  src/main/java/com/woowa/woowakit/domain/payment/domain/PaymentHandler.java
  src/main/java/com/woowa/woowakit/domain/payment/domain/PaymentService.java
  src/main/java/com/woowa/woowakit/global/config/AsyncConfig.java
  src/main/java/com/woowa/woowakit/global/config/PayConfig.java
  src/main/java/com/woowa/woowakit/global/config/WebClientConfig.java
  src/main/java/com/woowa/woowakit/infra/payment/toss/ThreadSleepClient.java
  src/main/java/com/woowa/woowakit/infra/payment/toss/TossPaymentClient.java
  src/main/resources/application.yml
  src/test/java/com/woowa/woowakit/domain/member/application/AuthServiceTest.java
  src/test/java/com/woowa/woowakit/infra/payment/toss/ThreadSleepClientTest.java
  src/test/java/com/woowa/woowakit/infra/payment/toss/TossPaymentClientTest.java
  src/test/resources/application.yml
Labels: enhancement, Pair

#106 feat: 비즈니스 메트릭 추가 (주문, 결제)
  src/main/java/com/woowa/woowakit/domain/order/application/OrderService.java
  src/main/java/com/woowa/woowakit/domain/payment/domain/PaySaveService.java
  src/main/java/com/woowa/woowakit/domain/payment/domain/PaymentHandler.java
  src/main/java/com/woowa/woowakit/global/config/ImageUploadConfig.java
  src/main/java/com/woowa/woowakit/global/config/MetricConfig.java
  src/main/java/com/woowa/woowakit/global/config/PayConfig.java
Labels: feature

#104 spring-rest-docs 를 이용해서 API 문서화 #103
  .gitignore
  build.gradle
  src/docs/asciidoc/apis.adoc
  src/main/java/com/woowa/woowakit/WoowakitApplication.java
  src/main/java/com/woowa/woowakit/domain/cart/dto/CartItemUpdateQuantityRequest.java
  src/main/java/com/woowa/woowakit/domain/order/dto/request/PreOrderCreateCartItemRequest.java
  src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductSpecification.java
  src/main/java/com/woowa/woowakit/global/config/JpaConfig.java
  src/test/java/com/woowa/woowakit/domain/auth/api/AuthControllerTest.java
  src/test/java/com/woowa/woowakit/domain/cart/api/CartItemControllerTest.java
  src/test/java/com/woowa/woowakit/domain/cart/domain/CartItemRepositoryTest.java
  src/test/java/com/woowa/woowakit/domain/member/application/AuthServiceTest.java
  src/test/java/com/woowa/woowakit/domain/order/api/OrderControllerTest.java
  src/test/java/com/woowa/woowakit/domain/order/application/OrderServiceTest.java
  src/test/java/com/woowa/woowakit/domain/order/dao/OrderRepositoryTest.java
  src/test/java/com/woowa/woowakit/domain/product/api/ProductControllerTest.java
  src/test/java/com/woowa/woowakit/domain/product/application/ProductServiceTest.java
  src/test/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/ExpirationDateProcessorTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StockConsistencyProcessorTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StockRepositoryTest.java
  src/test/java/com/woowa/woowakit/global/interceptor/AuthenticationInterceptorTest.java
  src/test/java/com/woowa/woowakit/restDocsHelper/PathParam.java
  src/test/java/com/woowa/woowakit/restDocsHelper/RequestFields.java
  src/test/java/com/woowa/woowakit/restDocsHelper/ResponseFields.java
  src/test/java/com/woowa/woowakit/restDocsHelper/RestDocsHelper.java
  src/test/java/com/woowa/woowakit/restDocsHelper/RestDocsTest.java
  src/test/java/integration/cart/CartIntegrationTest.java
Labels: documentation

#112 spring-rest-docs 오류 수정
  build.gradle
  src/test/java/com/woowa/woowakit/restDocsHelper/RestDocsHelper.java
Labels: documentation

#110 feat: 상품을 캐싱된 데이터를 바탕으로 조회할 수 있다. (#109)
  build.gradle
  src/docs/asciidoc/apis.adoc
  src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
  src/main/java/com/woowa/woowakit/domain/product/application/ProductService.java
  src/main/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryCustomImpl.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductSearchCondition.java
  src/main/java/com/woowa/woowakit/domain/product/dto/request/ProductSearchRequest.java
  src/main/java/com/woowa/woowakit/global/config/CacheConfig.java
  src/main/resources/application.yml
  src/test/java/com/woowa/woowakit/domain/product/api/ProductControllerTest.java
  src/test/java/com/woowa/woowakit/domain/product/application/ProductCacheTest.java
  src/test/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryTest.java
  src/test/java/com/woowa/woowakit/global/config/CacheTestConfig.java
  src/test/java/com/woowa/woowakit/restDocsHelper/RestDocsHelper.java
  src/test/java/integration/helper/ProductHelper.java
  src/test/java/integration/product/ProductIntegrationTest.java
  src/test/resources/application.yml
Labels: advanced

#118 feat: 주문 목록 조회 커서 적용 (#116)
  src/docs/asciidoc/apis.adoc
  src/main/java/com/woowa/woowakit/domain/order/api/OrderController.java
  src/main/java/com/woowa/woowakit/domain/order/application/OrderService.java
  src/main/java/com/woowa/woowakit/domain/order/dao/.gitkeep
  src/main/java/com/woowa/woowakit/domain/order/dao/OrderRepositoryCustom.java
  src/main/java/com/woowa/woowakit/domain/order/dao/OrderRepositoryCustomImpl.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderRepository.java
  src/main/java/com/woowa/woowakit/domain/order/dto/request/OrderSearchRequest.java
  src/test/java/com/woowa/woowakit/domain/order/api/OrderControllerTest.java
  src/test/java/com/woowa/woowakit/domain/order/dao/OrderRepositoryTest.java
Labels: bug, advanced

#119 refactor: 로그 보강
  src/main/java/com/woowa/woowakit/domain/cart/api/CartItemController.java
  src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
Labels: enhancement

#117 배치처리 최적화
  src/main/java/com/woowa/woowakit/WoowakitApplication.java
  src/main/java/com/woowa/woowakit/domain/auth/domain/Member.java
  src/main/java/com/woowa/woowakit/domain/model/BaseEntity.java
  src/main/java/com/woowa/woowakit/domain/model/Image.java
  src/main/java/com/woowa/woowakit/domain/order/domain/OrderItem.java
  src/main/java/com/woowa/woowakit/domain/product/application/StockProcessingService.java
  src/main/java/com/woowa/woowakit/domain/product/application/StockScheduler.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductImage.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductPrice.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/ProductSales.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/ExpirationDateProcessor.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/ExpiryDate.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/StockConsistencyProcessor.java
  src/main/java/com/woowa/woowakit/domain/product/domain/stock/StockRepository.java
  src/main/java/com/woowa/woowakit/domain/product/exception/StockBatchFailException.java
  src/main/java/com/woowa/woowakit/global/config/AsyncConfig.java
  src/main/java/com/woowa/woowakit/global/config/BatchAsyncConfig.java
  src/main/resources/application-prod.yml
  src/test/java/com/woowa/woowakit/domain/product/application/StockProcessingServiceTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/ExpirationDateProcessorTest.java
  src/test/java/com/woowa/woowakit/domain/product/domain/stock/StockConsistencyProcessorTest.java
Labels: advanced

#122 fix: 주문 목록 조회 이슈 해결
  src/main/java/com/woowa/woowakit/domain/order/dao/OrderRepositoryCustomImpl.java
  src/test/java/com/woowa/woowakit/domain/order/dao/OrderRepositoryTest.java
  src/test/java/integration/order/OrderIntegrationTest.java
Labels: enhancement

#124 fix: 잘못된 상품 id로 주문할 경우 예외 반환, cors 설정, 스레드풀 200으로 복귀
  src/main/java/com/woowa/woowakit/domain/order/domain/mapper/OrderMapper.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/woowa/woowakit/domain/order/domain/mapper/OrderMapperTest.java
Labels: fix

#125 fix: 상품 조회 이슈 해결 및 관리자 상품 조회 엔드 포인트 추가
  .github/workflows/dev-deploy.yml
  src/docs/asciidoc/apis.adoc
  src/main/java/com/woowa/woowakit/domain/product/api/ProductController.java
  src/main/java/com/woowa/woowakit/domain/product/application/ProductService.java
  src/main/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryCustom.java
  src/main/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryCustomImpl.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/AllProductSearchCondition.java
  src/main/java/com/woowa/woowakit/domain/product/domain/product/InStockProductSearchCondition.java
  src/main/java/com/woowa/woowakit/domain/product/dto/request/AllProductSearchRequest.java
  src/main/java/com/woowa/woowakit/domain/product/dto/request/InStockProductSearchRequest.java
  src/main/java/com/woowa/woowakit/domain/product/dto/response/ProductResponse.java
  src/main/java/com/woowa/woowakit/global/config/AsyncConfig.java
  src/main/java/com/woowa/woowakit/global/config/BatchAsyncConfig.java
  src/test/java/com/woowa/woowakit/domain/product/api/ProductControllerTest.java
  src/test/java/com/woowa/woowakit/domain/product/application/ProductCacheTest.java
  src/test/java/com/woowa/woowakit/domain/product/dao/ProductRepositoryTest.java
  src/test/java/integration/product/ProductIntegrationTest.java
Labels: fix

#126 로그인이 필요한 요청에 메시지 변경
  src/main/java/com/woowa/woowakit/global/error/.gitkeep
  src/main/java/com/woowa/woowakit/global/error/UnAuthorizationException.java
  src/main/java/com/woowa/woowakit/global/interceptor/UserAuthorityInterceptor.java
Labels: bug

#129 feat: 캐시 타는지 로그 추가
  src/main/java/com/woowa/woowakit/domain/product/application/ProductService.java
Labels: fix

#130 상품 재고가 부족한 경우 "상품의 재고가 부족합니다" 에러 메시지를 응답하도록 변경
  src/main/java/com/woowa/woowakit/domain/order/domain/mapper/OrderMapper.java
  src/main/java/com/woowa/woowakit/domain/order/exception/QuantityNotEnoughException.java
  src/test/java/integration/order/OrderIntegrationTest.java
  src/test/resources/application.yml
Labels: bug
